const SeedData = [
  {
    date: "2023-01-01",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [
      {
        role: "soupkitchen",
        timing: "5am-9am",
        type_of_volunteer: "individual",
        email: "awhuiyun@gmail.com",
        qty: 2,
      },
      {
        role: "soupkitchen",
        timing: "5am-9am",
        type_of_volunteer: "individual",
        email: "rachelwong@gmail.com",
        qty: 2,
      },
      {
        role: "soupkitchen",
        timing: "5am-9am",
        type_of_volunteer: "individual",
        email: "gavin@gmail.com",
        qty: 1,
      },
      {
        role: "soupkitchen",
        timing: "5am-9am",
        type_of_volunteer: "individual",
        email: "johnwong@gmail.com",
        qty: 2,
      },
      {
        role: "soupkitchen",
        timing: "9am-1pm",
        type_of_volunteer: "corporate",
        email: "ashley@gmail.com",
        qty: 24,
      },
      {
        role: "soupkitchen",
        timing: "1pm-5pm",
        type_of_volunteer: "individual",
        email: "lucas@gmail.com",
        qty: 4,
      },
      {
        role: "driver",
        timing: "1pm-5pm",
        type_of_volunteer: "individual",
        email: "lucas@gmail.com",
        qty: 1,
      },
      {
        role: "driver",
        timing: "1pm-5pm",
        type_of_volunteer: "individual",
        email: "kellyn@gmail.com",
        qty: 1,
      },
    ],
  },
  {
    date: "2023-01-02",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [
      {
        role: "soupkitchen",
        timing: "5am-9am",
        type_of_volunteer: "individual",
        email: "awhuiyun@gmail.com",
        qty: 3,
      },
      {
        role: "soupkitchen",
        timing: "5am-9am",
        type_of_volunteer: "individual",
        email: "rachelwong@gmail.com",
        qty: 1,
      },
      {
        role: "soupkitchen",
        timing: "9am-1pm",
        type_of_volunteer: "individual",
        email: "gavin@gmail.com",
        qty: 1,
      },
      {
        role: "soupkitchen",
        timing: "9am-1pm",
        type_of_volunteer: "individual",
        email: "johnwong@gmail.com",
        qty: 3,
      },
      {
        role: "soupkitchen",
        timing: "1pm-5pm",
        type_of_volunteer: "corporate",
        email: "ashley@gmail.com",
        qty: 16,
      },
      {
        role: "driver",
        timing: "1pm-5pm",
        type_of_volunteer: "individual",
        email: "simone@gmail.com",
        qty: 1,
      },
      {
        role: "driver",
        timing: "1pm-5pm",
        type_of_volunteer: "individual",
        email: "danielle@gmail.com",
        qty: 1,
      },
      {
        role: "driver",
        timing: "1pm-5pm",
        type_of_volunteer: "individual",
        email: "lily@gmail.com",
        qty: 1,
      },
    ],
  },
  {
    date: "2023-01-03",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-01-04",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-01-05",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-01-06",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-01-07",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-01-08",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-01-09",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-01-10",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-01-11",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-01-12",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-01-13",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-01-14",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-01-15",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-01-16",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-01-17",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-01-18",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-01-19",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-01-20",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-01-21",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-01-22",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-01-23",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-01-24",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-01-25",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-01-26",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-01-27",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-01-28",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-01-29",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-01-30",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-01-31",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-02-01",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-02-02",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-02-03",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-02-04",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-02-05",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-02-06",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-02-07",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-02-08",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-02-09",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-02-10",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-02-11",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-02-12",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-02-13",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-02-14",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-02-15",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-02-16",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-02-17",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-02-18",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-02-19",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-02-20",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-02-21",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-02-22",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-02-23",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-02-24",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-02-25",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-02-26",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-02-27",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-02-28",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-02-29",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
  {
    date: "2023-02-30",
    orig_slots_available: [
      { role: "soupkitchen", timing: "5am-9am", qty: 30 },
      { role: "soupkitchen", timing: "9am-1pm", qty: 30 },
      { role: "soupkitchen", timing: "1pm-5pm", qty: 30 },
      { role: "driver", timing: "5am-9am", qty: 30 },
      { role: "driver", timing: "9am-1pm", qty: 30 },
      { role: "driver", timing: "1pm-5pm", qty: 30 },
    ],
    sign_ups: [],
  },
];

module.exports = SeedData;
